// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn8_0F8SOPUFDbmGJ3enkOe0Ss09Gx1h4',
    appId: '1:771644577261:android:e239c370e06ba5881683e4',
    messagingSenderId: '771644577261',
    projectId: 'recycling-3fe66',
    storageBucket: 'recycling-3fe66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhzRUOea5CDzXREnRMvdLJZyFrXBvh70',
    appId: '1:771644577261:ios:f3a140fa37f3c6851683e4',
    messagingSenderId: '771644577261',
    projectId: 'recycling-3fe66',
    storageBucket: 'recycling-3fe66.appspot.com',
    iosClientId: '771644577261-1pc9gisme3ffbl7rnll0m9mi1i9b9j0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycling',
  );
}
